/**
 * GENERATED by scripts/tts/generate_narration_index.py — do not hand-edit.
 * Regenerate with: python3 scripts/tts/generate_narration_index.py
 *
 * Build-time bitset of "<slug>/<accent>" pairs whose
 * public/audio/<slug>/<accent>/narration.json exists. The player
 * consults this set synchronously on mount so the manifest is
 * fetched lazily on the first Listen press — and never probed at
 * all for lessons/accents with no narration yet.
 */
export const NARRATION_INDEX: ReadonlySet<string> = new Set([
  "agentic-ai-patterns/us",
  "anti-corruption-layer/us",
  "api-gateways/us",
  "authn-authz/us",
  "bff-backend-for-frontend/us",
  "caching-strategies/us",
  "cap-theorem/us",
  "cdns/us",
  "cloud-native-architecture/us",
  "consensus-raft/us",
  "data-partitioning/us",
  "design-instagram/us",
  "designing-ai-systems/us",
  "designing-chat-at-scale/us",
  "distributed-transactions/us",
  "domain-driven-design/us",
  "event-sourcing-cqrs/us",
  "graphql-vs-rest/us",
  "idempotency/us",
  "load-balancers/us",
  "message-queues/us",
  "microservices-patterns-pitfalls/us",
  "microservices-vs-monolith/us",
  "multi-region-active-active/us",
  "mvc-to-react/us",
  "nosql-databases/us",
  "observability/us",
  "rate-limiting/us",
  "replication-consistency-models/us",
  "resilience-patterns/us",
  "scaling-web-service/us",
  "sharding-strategies/us",
  "solid-principles/us",
  "stream-vs-batch/us",
  "url-shortener/us",
  "zero-trust-security/us",
]);
