/**
 * Pure, unit-testable helpers for neural lesson narration ("listen" tier 2).
 *
 * Tier 2 works like this: at build time every lesson's prose is synthesized
 * with Kokoro into `public/audio/<slug>/<accent>/narration.opus` (accent
 * "us" = af_heart, "uk" = bf_emma), plus a `narration.json` manifest
 * carrying per-word timestamps. At runtime this
 * module maps `audio.currentTime` to the word being spoken so the component
 * can karaoke-highlight the prose. Nothing here touches the DOM, `Audio`,
 * or `fetch` — the component owns all side effects, so this file is safe to
 * import anywhere (including the build-time prerender).
 *
 * Word identity contract (CRITICAL): the build-time synthesizer
 * (`scripts/tts/synthesize.py`) tokenizes each block with
 * `r"[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*"` and writes the resulting words
 * into the manifest in order. `tokenizeWords` below MUST produce the same
 * sequence for the same text — the DOM tagger consumes the manifest's word
 * list against the rendered text with this exact rule, and any divergence
 * degrades that block to whole-block highlighting.
 */

export interface NarrationWord {
  /** Surface form of the word as spoken, e.g. "don't". */
  text: string;
  /** Start time in seconds (media time of the opus file). */
  start: number;
  /** End time in seconds (media time of the opus file). */
  end: number;
}

export interface NarrationBlock {
  kind: 'title' | 'summary' | 'prose';
  /** Plain prose of the block (markdown stripped at build time). */
  text: string;
  words: NarrationWord[];
}

/** Neural narration accent: 'us' = Kokoro af_heart, 'uk' = Kokoro bf_emma. */
export type NarrationAccent = 'us' | 'uk';

export const NARRATION_ACCENTS: NarrationAccent[] = ['us', 'uk'];

const ACCENT_STORAGE_KEY = 'lesson-narration-accent';

/** Persisted learner accent preference; defaults to 'us'. SSR-safe. */
export function loadAccentPreference(): NarrationAccent {
  try {
    if (typeof window !== 'undefined' && 'localStorage' in window) {
      const v = window.localStorage.getItem(ACCENT_STORAGE_KEY);
      if (v === 'us' || v === 'uk') return v;
    }
  } catch {
    /* storage unavailable — fall through to default */
  }
  return 'us';
}

export function saveAccentPreference(accent: NarrationAccent): void {
  try {
    if (typeof window !== 'undefined' && 'localStorage' in window) {
      window.localStorage.setItem(ACCENT_STORAGE_KEY, accent);
    }
  } catch {
    /* storage unavailable — preference simply doesn't persist */
  }
}

export interface NarrationManifest {
  slug: string;
  /** Kokoro voice id used at build time, e.g. "af_heart". */
  voice: string;
  /** Per-accent id, "us" | "uk"; present in manifests generated by the
   *  current pipeline. Older manifests predate it — the player takes the
   *  accent from the URL path, so it stays optional here. */
  accent?: string;
  sampleRate: number;
  /** Total duration in seconds. */
  duration: number;
  /** Audio file name inside `public/audio/<slug>/<accent>/`, e.g. "narration.opus". */
  audio: string;
  /** Optional SHA-256 over block texts; present in manifests generated by
   *  the current extractor. Not validated here — staleness is detected via
   *  the aligned-block ratio, so older manifests without it are accepted. */
  contentHash?: string;
  blocks: NarrationBlock[];
}

/**
 * Runtime trust boundary for the fetched manifest: the manifest drives a
 * binary search (which assumes numeric, non-decreasing starts) and its
 * `audio` field is interpolated into the audio URL, so validate values,
 * not just shapes. Rejects → the proven Web Speech fallback renders.
 */
export const isValidManifest = (value: unknown): value is NarrationManifest => {
  if (typeof value !== 'object' || value === null) return false;
  const m = value as Record<string, unknown>;
  if (typeof m.slug !== 'string' || m.slug.length === 0) return false;
  if (typeof m.duration !== 'number' || !Number.isFinite(m.duration) || m.duration <= 0)
    return false;
  if (typeof m.audio !== 'string' || !/^[A-Za-z0-9._-]+\.opus$/.test(m.audio))
    return false;
  if (
    m.accent !== undefined &&
    m.accent !== null &&
    m.accent !== 'us' &&
    m.accent !== 'uk'
  )
    return false;
  if (!Array.isArray(m.blocks)) return false;
  return m.blocks.every((b) => {
    if (typeof b !== 'object' || b === null) return false;
    const bb = b as Record<string, unknown>;
    if (typeof bb.text !== 'string') return false;
    if (!Array.isArray(bb.words)) return false;
    // The karaoke lookup binary-searches word starts, so they must be
    // non-decreasing within a block (the build enforces this with a
    // monotonic clamp; a hand-edited manifest that violates it is corrupt).
    let prevStart = 0;
    return (bb.words as unknown[]).every((w) => {
      if (typeof w !== 'object' || w === null) return false;
      const ww = w as Record<string, unknown>;
      const ok =
        typeof ww.text === 'string' &&
        typeof ww.start === 'number' &&
        Number.isFinite(ww.start) &&
        typeof ww.end === 'number' &&
        Number.isFinite(ww.end) &&
        ww.start >= 0 &&
        ww.start <= ww.end &&
        ww.start >= prevStart;
      if (typeof ww.start === 'number') prevStart = ww.start;
      return ok;
    });
  });
};

const WORD_RE = /[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*/gu;

/**
 * Canonical word tokenizer. Must stay in lockstep with the build-time
 * tokenizer in `scripts/tts/synthesize.py` (see module docstring).
 * Cross-language contract: if you change tokenization here, change
 * `tokenize_words()` in `scripts/tts/synthesize.py` and update both
 * parity tests (TokenizeParityTest in test_align.py, narration.test.ts).
 */
export function tokenizeWords(text: string): string[] {
  WORD_RE.lastIndex = 0;
  return text.match(WORD_RE) ?? [];
}

/** Fuzzy word comparison for aligning manifest words with rendered text. */
export function normalizeWordToken(word: string): string {
  return word.toLowerCase().replace(/[^\p{L}\p{N}]/gu, '');
}

const baseUrl = (): string => {
  const b =
    typeof import.meta !== 'undefined' && import.meta.env
      ? (import.meta.env.BASE_URL as string | undefined)
      : undefined;
  return b && b.length > 0 ? b : '/';
};

/** URL of the timing manifest, e.g. `/<base>/audio/<slug>/us/narration.json`. */
export function narrationJsonUrl(slug: string, accent: NarrationAccent): string {
  return `${baseUrl()}audio/${slug}/${accent}/narration.json`;
}

/** URL of the audio file described by a loaded manifest. */
export function narrationAudioUrl(
  slug: string,
  accent: NarrationAccent,
  manifest: NarrationManifest,
): string {
  return `${baseUrl()}audio/${slug}/${accent}/${manifest.audio}`;
}

export interface FlatWord {
  /** Index into `manifest.blocks`. */
  block: number;
  /** Index of the word inside its block. */
  index: number;
  text: string;
  start: number;
  end: number;
}

/** Flatten all block words into one time-ordered array for binary search. */
export function flattenWords(manifest: NarrationManifest): FlatWord[] {
  const flat: FlatWord[] = [];
  manifest.blocks.forEach((block, b) => {
    block.words.forEach((w, i) => {
      flat.push({ block: b, index: i, text: w.text, start: w.start, end: w.end });
    });
  });
  return flat;
}

/**
 * Binary search: index of the word active at media time `t`, i.e. the last
 * word with `start <= t < end`. Returns -1 when nothing is spoken at `t`
 * (before the first word, or at/past the end).
 */
export function findActiveWordIndex(
  flat: readonly FlatWord[],
  t: number,
): number {
  let lo = 0;
  let hi = flat.length - 1;
  let best = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const w = flat[mid];
    if (w.start <= t) {
      best = mid;
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }
  if (best === -1) return -1;
  return t < flat[best].end ? best : -1;
}

const normBlockText = (s: string): string =>
  s.toLowerCase().replace(/\s+/g, ' ').trim();

/**
 * Mirror of the extractor's `_speakable_punct` (scripts/tts/extract_narration.py):
 * symbols the TTS voice speaks as words. The manifest holds the *spoken*
 * form ("about 120 requests/second") while the DOM holds the written form
 * ("~120 requests/second"); applying the same expansion to both sides lets
 * those blocks align. Keep in sync with the extractor.
 *
 * `expandPunctWithMap` is the single implementation: a left-to-right scan
 * applying the same replacements `speakablePunct` documents, while recording
 * for every emitted character which original character it derives from.
 * Because no replacement output ever contains a matchable pattern, this
 * single pass is equivalent to the extractor's sequential replaces.
 */
export interface PunctExpansion {
  expanded: string;
  /**
   * For each char of `expanded`, the index in the original string it derives
   * from. Chars inserted by a replacement map to the replaced range, with
   * the replacement's first/last non-space chars attributed to the range's
   * first/last char — so a spoken token resolves back to the full written
   * symbol ("about" -> "~", "to" -> "->").
   */
  origOf: number[];
}

export function expandPunctWithMap(text: string): PunctExpansion {
  let expanded = '';
  const origOf: number[] = [];
  const emitRaw = (idx: number): void => {
    expanded += text[idx];
    origOf.push(idx);
  };
  const emitRep = (rep: string, from: number, to: number): void => {
    const chars = Array.from(rep);
    const firstWord = chars.findIndex((c) => c !== ' ');
    const lastWord =
      chars.length - 1 - [...chars].reverse().findIndex((c) => c !== ' ');
    chars.forEach((c, k) => {
      expanded += c;
      if (k < firstWord) origOf.push(from);
      else if (k > lastWord) origOf.push(to - 1);
      else origOf.push(k === firstWord ? from : to - 1);
    });
  };
  let i = 0;
  while (i < text.length) {
    if (text.startsWith('->', i)) {
      emitRep(' to ', i, i + 2);
      i += 2;
    } else if (text.startsWith('=>', i)) {
      emitRep(' to ', i, i + 2);
      i += 2;
    } else if (text[i] === '&') {
      emitRep(' and ', i, i + 1);
      i += 1;
    } else if (text[i] === '%' && i > 0 && /\d/.test(text[i - 1])) {
      emitRep(' percent', i, i + 1);
      i += 1;
    } else if (text[i] === '~') {
      emitRep(' about ', i, i + 1);
      i += 1;
    } else {
      emitRaw(i);
      i += 1;
    }
  }
  return { expanded, origOf };
}

export const speakablePunct = (text: string): string =>
  expandPunctWithMap(text).expanded;

export interface ExpandedToken {
  /** The spoken token text, from the punctuation-expanded form. */
  text: string;
  /** Char range in the ORIGINAL string this token was spoken from. */
  origStart: number;
  origEnd: number;
}

/**
 * Tokenize `raw` in its spoken (punctuation-expanded) form, remembering
 * where each spoken token came from in the raw text. The manifest's word
 * list is tokenized from expanded text, so matching the DOM against these
 * tokens is what lets blocks containing "~", "&", "->" etc. keep
 * word-level highlighting instead of degrading to block level.
 */
export function expandTokens(raw: string): ExpandedToken[] {
  const { expanded, origOf } = expandPunctWithMap(raw);
  WORD_RE.lastIndex = 0;
  const tokens: ExpandedToken[] = [];
  let m: RegExpExecArray | null;
  while ((m = WORD_RE.exec(expanded)) !== null) {
    const origStart = origOf[m.index];
    const origEnd = origOf[m.index + m[0].length - 1] + 1;
    tokens.push({ text: m[0], origStart, origEnd });
  }
  return tokens;
}

/**
 * Align manifest blocks to rendered DOM blocks by normalized text equality.
 * The DOM side is first run through {@link speakablePunct} so blocks whose
 * spoken form expands symbols ("~" → "about") still match their written
 * form. Returns, per manifest block, the index of the first still-unclaimed
 * DOM block with identical text, or `null` when no DOM block matches.
 *
 * Note: a `null` entry means the block gets NO highlight while its words
 * are spoken — only blocks that aligned but failed word-level tagging fall
 * back to whole-block highlighting (see `wrapWordSpans`).
 */
export function alignBlocks(
  manifestBlocks: readonly { text: string }[],
  domTexts: readonly string[],
): (number | null)[] {
  const claimed = new Set<number>();
  return manifestBlocks.map((mb) => {
    const want = normBlockText(mb.text);
    for (let d = 0; d < domTexts.length; d++) {
      if (claimed.has(d)) continue;
      if (normBlockText(speakablePunct(domTexts[d])) === want) {
        claimed.add(d);
        return d;
      }
    }
    return null;
  });
}

export interface WordSpanPart {
  kind: 'gap' | 'word';
  text: string;
}

export interface WordSpanPlan {
  parts: WordSpanPart[];
  /** How many manifest words were consumed from the front of the queue. */
  consumed: number;
}

/**
 * Pure core of the DOM word tagger: given one text node's raw text and the
 * remaining expected words (front of queue), decide how to split the node
 * into gap/word spans. Returns `null` when the node's word tokens don't
 * match the expected words — the caller then abandons word-level tagging
 * for that block and falls back to whole-block highlighting.
 *
 * Matching is fuzzy (`normalizeWordToken`) so typographic quotes or case
 * differences between build-time text and rendered text don't break it.
 * Tokens are matched in their *spoken* (punctuation-expanded) form while
 * the emitted spans keep the original written text: a DOM "~10x" matches
 * the manifest words ["about", "10x"] and the "~" itself is what lights up
 * while "about" is spoken.
 */
export function planWordSpans(
  text: string,
  words: readonly string[],
): WordSpanPlan | null {
  const parts: WordSpanPart[] = [];
  let consumed = 0;
  let lastOrigEnd = 0;

  // Walk spoken-form tokens in order; everything between them is a gap.
  for (const tok of expandTokens(text)) {
    if (tok.origStart > lastOrigEnd) {
      parts.push({ kind: 'gap', text: text.slice(lastOrigEnd, tok.origStart) });
    }
    const expected = words[consumed];
    if (
      expected === undefined ||
      normalizeWordToken(tok.text) !== normalizeWordToken(expected)
    ) {
      return null;
    }
    parts.push({ kind: 'word', text: text.slice(tok.origStart, tok.origEnd) });
    consumed += 1;
    lastOrigEnd = tok.origEnd;
  }
  if (lastOrigEnd < text.length) {
    parts.push({ kind: 'gap', text: text.slice(lastOrigEnd) });
  } else if (parts.length === 0) {
    parts.push({ kind: 'gap', text });
  }
  return { parts, consumed };
}
