// P1 (course Q&A agent): tests for the retrieval index and its wiring.
//
// The bundled index (worker/src/qa/qa-index.ts) is generated by
// scripts/qa/build-index.ts and committed, so these tests run against the
// real artifact -- retrieval quality is tested, not mocked.

import { describe, expect, it } from 'vitest';
import { runQaTurn } from './graph';
import { QA_INDEX } from './qa-index';
import {
  D1ChunkStore,
  readLessonText,
  searchLessons,
  titleForSlug,
  tokenize,
  uniqueSources,
  type ChunkStore,
  type D1Like,
} from './retrieval';
import { handleQaChat } from './routes';

const indexJson = JSON.stringify(QA_INDEX);

// Distinctive strings taken from <Quiz> blocks in content/lessons/*.mdx.
// None of them may appear in the bundled index: the whole Quiz block
// (questions, options, correctIndex) is stripped before chunking. (The
// migration SQL gets the same check in scripts/qa/build-index.test.ts,
// which runs under node types and can read files.)
const QUIZ_STRINGS = [
  'correctIndex',
  'The phone line between your two diners is cut. A CP system will...',
  "Keep seating customers and serving whatever's on the board, stale or not",
  'Two nodes that are both alive and reachable by clients, but unable to reach each other',
  'Kevin the intern keeps retrying a failed payment API. Which two guardrails',
  'Reasoning tokens bill as output tokens, so heavy reasoning pushes a step',
];

describe('tokenize', () => {
  it('lowercases, drops stopwords and single characters', () => {
    expect(tokenize('The CAP Theorem!')).toEqual(['cap', 'theorem']);
    expect(tokenize('a of to')).toEqual([]);
    expect(tokenize('x')).toEqual([]);
  });

  it('keeps meaningful short tokens and splits on punctuation', () => {
    expect(tokenize('db S3 2pc')).toEqual(['db', 's3', '2pc']);
    expect(tokenize('cache-aside')).toEqual(['cache', 'aside']);
  });

  it('is deterministic', () => {
    const q = 'What is the CAP theorem and why does it matter?';
    expect(tokenize(q)).toEqual(tokenize(q));
  });
});

describe('searchLessons over the real bundled index', () => {
  it('ranks the CAP theorem lesson first for "CAP theorem"', () => {
    const results = searchLessons(QA_INDEX, 'CAP theorem', 5);
    expect(results.length).toBeGreaterThan(0);
    expect(results[0]?.slug).toBe('cap-theorem');
    expect(results[0]?.score).toBeGreaterThan(0);
    expect(results[0]?.title).toBe('The CAP Theorem');
    expect(results[0]?.excerpt.length).toBeGreaterThan(0);
  });

  it('finds consistent hashing content', () => {
    const results = searchLessons(QA_INDEX, 'consistent hashing', 5);
    expect(results.length).toBeGreaterThan(0);
    expect(results[0]?.slug).toBe('sharding-strategies');
  });

  it('finds the load balancer lesson', () => {
    const results = searchLessons(QA_INDEX, 'what is a load balancer', 5);
    expect(results.length).toBeGreaterThan(0);
    expect(results[0]?.slug).toBe('load-balancers');
  });

  it('returns empty for gibberish and empty queries', () => {
    expect(searchLessons(QA_INDEX, 'zxqv wjbmpl kzx', 5)).toEqual([]);
    expect(searchLessons(QA_INDEX, '', 5)).toEqual([]);
    expect(searchLessons(QA_INDEX, 'the and of', 5)).toEqual([]);
    expect(searchLessons(QA_INDEX, 'CAP theorem', 0)).toEqual([]);
  });

  it('is deterministic and ranks ties by chunk id', () => {
    const a = searchLessons(QA_INDEX, 'cache eviction', 5);
    const b = searchLessons(QA_INDEX, 'cache eviction', 5);
    expect(a).toEqual(b);
  });

  it('respects k', () => {
    expect(searchLessons(QA_INDEX, 'caching', 2)).toHaveLength(2);
  });

  it('covers every lesson with at least one chunk', () => {
    const slugs = new Set(QA_INDEX.chunks.map((c) => c.slug));
    expect(slugs.size).toBe(36);
    expect(QA_INDEX.chunkCount).toBe(QA_INDEX.chunks.length);
  });
});

describe('quiz answer exclusion', () => {
  it('bundled index contains no quiz material', () => {
    for (const s of QUIZ_STRINGS) {
      expect(indexJson, `leaked: ${s}`).not.toContain(s);
    }
  });

  it('no chunk excerpt looks like a quiz option list', () => {
    for (const c of QA_INDEX.chunks) {
      expect(c.excerpt).not.toContain('correctIndex');
    }
  });
});

describe('citation helpers', () => {
  it('uniqueSources dedupes lessons preserving rank order', () => {
    const results = searchLessons(QA_INDEX, 'CAP theorem', 5);
    const sources = uniqueSources(results);
    expect(sources[0]).toEqual({ slug: 'cap-theorem', title: 'The CAP Theorem' });
    expect(new Set(sources.map((s) => s.slug)).size).toBe(sources.length);
  });

  it('titleForSlug resolves known slugs and misses unknown ones', () => {
    expect(titleForSlug(QA_INDEX, 'cap-theorem')).toBe('The CAP Theorem');
    expect(titleForSlug(QA_INDEX, 'nope-not-a-lesson')).toBeUndefined();
  });
});

describe('readLessonText', () => {
  const store: ChunkStore = {
    getLessonChunks: async (slug: string) => {
      if (slug !== 'demo') return [];
      // Deliberately out of order -- the helper must sort by ordinal.
      return [
        { ordinal: 1, text: 'second' },
        { ordinal: 0, text: 'first' },
      ];
    },
  };

  it('concatenates chunks in ordinal order', async () => {
    expect(await readLessonText(store, 'demo')).toBe('first\n\nsecond');
  });

  it('returns empty for unknown slugs', async () => {
    expect(await readLessonText(store, 'missing')).toBe('');
  });

  it('caps length with a truncation marker', async () => {
    const big: ChunkStore = {
      getLessonChunks: async () => [{ ordinal: 0, text: 'x'.repeat(100) }],
    };
    const out = await readLessonText(big, 'demo', 10);
    expect(out).toBe(`${'x'.repeat(10)}\n\n[…truncated]`);
  });
});

describe('D1ChunkStore', () => {
  /** Minimal D1 double covering only the qa_chunks SELECT shape. */
  function fakeD1(rows: Array<{ slug: string; ordinal: number; text: string }>): D1Like {
    return {
      prepare: (sql: string) => ({
        bind: (...params: unknown[]) => ({
          all: async <T>() => {
            expect(sql).toContain('FROM qa_chunks WHERE slug = ?');
            const slug = params[0] as string;
            const results = rows
              .filter((r) => r.slug === slug)
              .sort((a, b) => a.ordinal - b.ordinal)
              .map((r) => ({ ordinal: r.ordinal, text: r.text }));
            return { results: results as T[] };
          },
        }),
      }),
    };
  }

  it('reads a lesson in ordinal order from D1', async () => {
    const store = new D1ChunkStore(
      fakeD1([
        { slug: 'cap-theorem', ordinal: 1, text: 'b' },
        { slug: 'cap-theorem', ordinal: 0, text: 'a' },
        { slug: 'other', ordinal: 0, text: 'zzz' },
      ]),
    );
    expect(await readLessonText(store, 'cap-theorem')).toBe('a\n\nb');
    expect(await readLessonText(store, 'missing')).toBe('');
  });
});

/** Tiny D1 double for the checkpointer SQL shapes used by runQaTurn. */
class CheckpointD1 {
  rows = new Map<string, string>();

  prepare(sql: string): {
    bind(...params: unknown[]): {
      first<T>(): Promise<T | null>;
      run(): Promise<{ success: boolean }>;
    };
  } {
    const normalized = sql.replace(/\s+/g, ' ').trim().toUpperCase();
    return {
      bind: (...params: unknown[]) => ({
        first: async <T>(): Promise<T | null> => {
          if (normalized.startsWith('SELECT STATE, UPDATED_AT FROM QA_CHECKPOINTS')) {
            const state = this.rows.get(params[0] as string);
            return (state ? { state, updated_at: 't' } : null) as T | null;
          }
          throw new Error(`unsupported: ${sql}`);
        },
        run: async () => {
          if (normalized.startsWith('INSERT INTO QA_CHECKPOINTS')) {
            this.rows.set(params[0] as string, params[1] as string);
            return { success: true };
          }
          throw new Error(`unsupported: ${sql}`);
        },
      }),
    };
  }
}

describe('chat flow citations (P1)', () => {
  // Minimal model: never calls tools, returns a fixed answer. Triage still
  // runs (deterministic), so the CAP question reaches the model and the
  // gibberish is refused before any model spend.
  const fakeModel = {
    complete: async () => ({ text: 'fake answer', toolCalls: [] }),
    summarize: async () => 'fake summary',
  };
  const emptyStore = { getLessonChunks: async () => [] };

  it('runQaTurn attaches real lesson slugs as sources', async () => {
    const db = new CheckpointD1();
    const turn = await runQaTurn(db as unknown as D1Database, 'sess-1', 'What is the CAP theorem?', {
      model: fakeModel,
      chunkStore: emptyStore,
    });
    expect(turn.sources).toContain('cap-theorem');
    // Gibberish retrieves nothing -- sources stay empty, honestly.
    const turn2 = await runQaTurn(db as unknown as D1Database, 'sess-2', 'zxqv wjbmpl kzx', {
      model: fakeModel,
      chunkStore: emptyStore,
    });
    expect(turn2.sources).toEqual([]);
  });
});
