#!/usr/bin/env python3
"""Generate the build-time has-narration bitset for lazy narration loading.

Scans public/audio/<slug>/<accent>/narration.json and writes
src/lib/narration-index.generated.ts: a tiny Set of "<slug>/<accent>"
keys the site consults synchronously on lesson mount, so the player
fetches a manifest only when the learner presses Listen — and never
probes at all for lessons/accents with no narration.

The player must NEVER hand-edit the generated module: re-run this script
after synthesizing (or removing) narration:

    python3 scripts/tts/generate_narration_index.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AUDIO_OUT = REPO_ROOT / "public" / "audio"
OUT_FILE = REPO_ROOT / "src" / "lib" / "narration-index.generated.ts"


def scan_narration_keys() -> list[str]:
    """Return sorted "<slug>/<accent>" keys with a narration.json present."""
    keys: list[str] = []
    if not AUDIO_OUT.is_dir():
        return keys
    for slug_dir in sorted(AUDIO_OUT.iterdir()):
        if not slug_dir.is_dir():
            continue
        for accent_dir in sorted(slug_dir.iterdir()):
            if accent_dir.is_dir() and (accent_dir / "narration.json").is_file():
                keys.append(f"{slug_dir.name}/{accent_dir.name}")
    return keys


def render_module(keys: list[str]) -> str:
    entries = "\n".join(f'  "{k}",' for k in keys)
    return (
        "/**\n"
        " * GENERATED by scripts/tts/generate_narration_index.py — do not hand-edit.\n"
        " * Regenerate with: python3 scripts/tts/generate_narration_index.py\n"
        " *\n"
        " * Build-time bitset of \"<slug>/<accent>\" pairs whose\n"
        " * public/audio/<slug>/<accent>/narration.json exists. The player\n"
        " * consults this set synchronously on mount so the manifest is\n"
        " * fetched lazily on the first Listen press — and never probed at\n"
        " * all for lessons/accents with no narration yet.\n"
        " */\n"
        "export const NARRATION_INDEX: ReadonlySet<string> = new Set([\n"
        f"{entries}\n"
        "]);\n"
    )


def main() -> int:
    keys = scan_narration_keys()
    OUT_FILE.write_text(render_module(keys), encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)}: {len(keys)} narration packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
